server:
  port: 8087 #服务端口
spring:
  application:
    name: bigdate-apigateway #指定服务名
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://zpc:123456@127.0.0.1:8100/eureka/,http://zpc:123456@127.0.0.1:9100/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}###${server.port} #指定实例id

zuul:
  routes: #定义服务转发规则
    bigdate-helpcenter: #item-service这个名字是任意写的
      path: /bigdate-helpcenter/** #匹配item-service的请求app-item服务
      #url: http://127.0.0.1:8081 #真正的微服务地址
      serviceid: bigdate-helpcenter
#    order-service: #名字尽量和业务系统相关
#      path: /order-service/** #匹配order-service的请求app-order服务
#      serviceid: app-order
